### PR TITLE
Azure AD -> Entra rebranding

### PR DESCRIPTION
**Pull request by ckittel**

### CODE REVIEW

**Comment by xpouyat** [comment]
Hello @ckittel 
Did you test the terraform deployment with the updates, or should I test it ?

**Comment by ckittel** [comment]
I did not test, it was just a find and replace action.  Please test as you see fit.

**Comment by ckittel** [comment]
This is the last repo in this org that need to have the rebranding PR merged.  Do you have an update on this @xpouyat?

**Comment by xpouyat** [comment]
Hi, @ckittel, sorry I did not have time yet to redeploy Gridwich and in order to test your changes. This will require several hours of work. If this is urgent, I can accept the PR without testing...

**Comment by ckittel** [comment]
You're one of the few repos left on the tracking list. Urgent no, but with fewer repos on the list now, you'll be standing out more in the dwindling crowd. We are targeting to have all repos resolved by the end of this month.

Proceed as you see appropriate.

**Comment by xpouyat** [comment]
I started testing the terraform deployment. Added a couple of commits to your PR. Still working on it as testing is not successful yet.

**Comment by xpouyat** [comment]
Terraform deployment was successful

**Review by xpouyat — APPROVED** [review]

**Pull request merged**
