### PR TITLE
Add back the fake certificate so the unit tests are successful

### PR DESCRIPTION
**Pull request by xpouyat**
I am one of the developer of the project.
Current public code does not ship the fake pfx certificate, probably because pfx are typically ignored in .gitignore.
Problem is that it creates 6 failures in the unit tests.
2022-01-25_22h35_15

This pull request adds back the pfx file so the unit tests work fine.

### CODE REVIEW

**Review by magrande — APPROVED** [review]
LGTM, thanks @xpouyat

**Comment by ckittel** [comment]
You might consider just using an `​!`​ ignore pattern lower in the existing ​`.gitignore`​​ file, to override that for this _specific_ directory.  The comment above your line of code change seems to indicate that the directory was already excluded (but doesn't look like it is anymore).  Alternatively, you can also force add a file that is normally excluded so you don't need to update the `.gitignore` rules.

@xpouyat -- do you have permissions necessary to merge this?  If not, since you're a developer on this, I'm for sure eager to get you the permissions you need to maintain this.  LMK who (github usernames) all needs access that currently doesn't have it.

**Comment by xpouyat** [comment]
@ckittel thanks for your comment.
You are right, another option would be to modify the .gitignore file for this specific pfx file. By default, pfx are excluded. May be this is a better option. I will think about it.
I don't have the right to merge this. Please provide me the right, thanks! I will still open PR for review anyway.
We are testing gridwich for a project and I already updated packages in my fork and looking to other updates as the code is two years old and some items are deprecated and generate additional warnings.

**Comment by ckittel** [comment]
Perfect, so just to confirm, only yourself needs to be added?  Any other co-contributors?

**Comment by xpouyat** [comment]
Myself and @flecoqui 
Thanks!

**Comment by ckittel** [comment]
Both you and @flecoqui now have appropriate access to maintain your own assets :)  Any notable changes, be sure to also update the reference architecture on docs.microsoft.com -- don't want them to stray apart.  As for reviews, typically Azure Architecture Center engineers won't be involved, but if you would like anyone from our team to provide them (kinda like above), you're welcome to ping us!

So, you're free to merge/maintain.  If there are others that need to be added later, just let me know.  Cheers!

There is a branch policy here that requires users with "write" access to the repo be involved in a review, but you can override that with a little checkbox if needed.  (@magrande above, while on our team, doesn't actually have write access so his review didn't "count" from the branch policy's perspective, for example)

**Review by ckittel — APPROVED** [review]
:)

**Pull request merged**
